services:

  stats-db:
    image: postgres:16.1
    container_name: "stats-db"
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  main-db:
    image: postgres:16.1
    container_name: "main-db"
    ports:
      - "6542:5432"
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 10s
      interval: 10s
      retries: 20
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root